spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: google
          uri: https://www.google.com
          predicates:
            - Path=/test/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info